### ISSUE TITLE
Consider design pattern of lables over namespaces

### ISSUE THREAD

**Issue by lazzarello** [upmc-enterprises/emmie#19]
I don't yet have an opinion on this matter though I read through the development docs regarding namespaces and [labels](http://kubernetes.io/docs/user-guide/labels/). It appears the k8s authors recommend labels for deploying feature branches into a [single namespace](http://kubernetes.io/docs/user-guide/namespaces/).

I'm moving ahead with my own project based on your work (thanks!) though I would like to further investigate using labels in my fork.

**Comment by stevesloka** [comment]
Using namespaces for how we're deploying is actually the correct usage. Namespaces give you a separate "environments" to deploy to and all object within a namespace are unique. 

Since emmie copies all objects from the `template` namespace into the feature branch namespace. So you can have a deployment named `webapp` in one namespace, and other deployment named the same in another and they won't conflict.

Also, dns lookups are done by namespace. So if your API calls a database which has a service with name `mysql`, then your app's config doesn't have to change, each app deployed to the namespace will look for `mysql:3306` and they will use the database within your namespace.

**Comment by lazzarello** [comment]
Makes sense. Thanks for unpacking your design motivation.
